#ifndef BUILD_INFO_H
#define BUILD_INFO_H

#define LLAMA_BUILD_NUMBER 999
#define LLAMA_COMMIT "KOBOLDCPP"
#define LLAMA_COMPILER "KCPP"
#define LLAMA_TARGET "KCPP"
#define LLAMA_BUILD_COMMIT "KOBOLDCPP"
#define LLAMA_BUILD_COMPILER "KCPP"
#define LLAMA_BUILD_TARGET "KCPP"

#endif // BUILD_INFO_H
