make -j tests
export MTL_DEBUG_LAYER=1
export MTL_SHADER_VALIDATION=1
export MTL_SHADER_VALIDATION_REPORT_TO_STDERR=1
export MTL_SHADER_VALIDATION_FAIL_MODE=allow
export MTL_DEBUG_LAYER_VALIDATE_STORE_ACTIONS=1
export MTL_DEBUG_LAYER_VALIDATE_LOAD_ACTIONS=1
./tests/test-backend-ops -b Metal -o MUL_MAT
