#!/bin/bash

printf "# this file is auto-generated by scripts/gen-authors.sh\n\n" > AUTHORS
printf "List of llama.cpp contributors in chronological order of their first commit:\n\n" >> AUTHORS

git log --format='%an <%ae>' --reverse --date=short master | awk '!seen[$0]++' >> AUTHORS
